### ISSUE TITLE
compas view_2- Pycharm- Not working 

### ISSUE THREAD

**Issue by pzjayenn** [compas-dev/compas_view2#142]
**Describe the bug**

Compas view_2 not working in pycharm Mac OS M1

**To Reproduce**

running any code which involves compas view_2 fails and the error is attached.

**Expected behavior**

**Screenshots**

  warnings.warn('Selected binding "{}" could not be found, '
qt.qpa.drawing: Layer-backing is always enabled.  QT_MAC_WANTS_LAYER/_q_mac_wantsLayer has no effect.
Traceback (most recent call last):
  File "/Users/---/PycharmProjects/pythonProject/Matrix.py", line 3, in <module>
    viewer = App()
  File "/Users/---/venv/lib/python3.10/site-packages/compas_view2/app/app.py", line 192, in __init__
    self.init()
  File "/Users/---/venv/lib/python3.10/site-packages/compas_view2/app/app.py", line 205, in init
    self._init_menubar(self.config.get('menubar'))
  File "/Users/---/venv/lib/python3.10/site-packages/compas_view2/app/app.py", line 468, in _init_menubar
    self._add_menubar_items(items, self.menubar)
  File "/Users--/venv/lib/python3.10/site-packages/compas_view2/app/app.py", line 499, in _add_menubar_items
    self._add_menubar_items(item['items'], menu)
  File "/Users/---/venv/lib/python3.10/site-packages/compas_view2/app/app.py", line 501, in _add_menubar_items
    radio = QtWidgets.QActionGroup(self.window, exclusive=True)
TypeError: 'exclusive' is an unknown keyword argument

- Mac OS M1
- Python version [3.10]
- Python package manager [conda using pycharm community versiion]

**Comment by brgcode** [comment]
hi,

thanks for reporting!
do i understand correctly that this does not happen when you run the viewer from the command line or in VS Code?

**Comment by pzjayenn** [comment]
I used pycharm and terminal . I could not install pyside 2 and hence installed pyside 6.

**Comment by GeneKao** [comment]
@Licini  @brgcode Ziqi had a problem with his new MacBook that has an M1 chip, so he couldn't install qt5, I think he installed qt and replaced this line https://github.com/compas-dev/compas_view2/blob/de7f4d5f4be94610d1daee6cd3ad0c668dbcce13/src/compas_view2/views/view.py#L269 in the function `wheelEvent` with `degrees = event.angleDelta().y() / 8` and problem was resolved. Not sure if they are the same problem, but maybe this helps.

**Comment by pzjayenn** [comment]
I tried a few things but I'm still getting following errors :


 cannot import name 'NurbsSurface' from 'compas.geometry'

Selected binding "pyside2" could not be found, using "pyqt6"
  warnings.warn('Selected binding "{}" could not be found, '

qt.qpa.drawing: Layer-backing is always enabled.  QT_MAC_WANTS_LAYER/_q_mac_wantsLayer has no effect.
Traceback (most recent call last):

radio = QtWidgets.QActionGroup(self.window, exclusive=True)
TypeError: 'exclusive' is an unknown keyword argument

'exclusive' is an unknown keyword argument

**Comment by brgcode** [comment]
i'm a bit confused about the PySide2/6 problem. could you briefly explain how you installed `compas_view2`? so i know which problem that actually needs solving...

thanks!

**Comment by pzjayenn** [comment]
I am using pycharm and installed compas_view2 within pycharm.  As pyside 2 was a dependency, I tried installing it but couldn't and instead installed pyside 6 and the error I mentioned is what showed up after. I have attached screenshots of pycharm preferences of the installed packages. Thank you.

Moreover I can run basic compas programs which involve points vectors etc. However as soon as compas_view 2 is to be executed within the program, its crashes and spews out the errors I mentioned.
<img width="897" alt="Screen Shot 2022-07-08 at 7 39 33 AM" src="https://user-images.githubusercontent.com/107090168/177903132-51294aa9-ae18-4f2c-86d8-3f8728d863a4.png">
<img width="897" alt="Screen Shot 2022-07-08 at 7 39 55 AM" src="https://user-images.githubusercontent.com/107090168/177903136-4f48fe10-aff7-4131-852d-1ffbbae22cda.png">

**Comment by brgcode** [comment]
hi, i should have been more clear. i meant to ask if you installed the package via conda or in some other way. and if the latter, could you describe the installation steps?

**Comment by pzjayenn** [comment]
I opened thr python interpreter in pycharm as shown in screen shot . Clicked on plus button on the top  left   corner to add package and searched for compas view 2 and installed it.

**Comment by brgcode** [comment]
i guess `pyside6` is required because of the `qtpy` dependency we added recently. will fix this in the next release which should be out soon.

btw, the arm64 version of the package is available since yesterday. not sure if the problem will go away, but perhaps it is worth a try...

**Comment by pzjayenn** [comment]
Thank you so much. I'll try that definitely.

**Comment by pzjayenn** [comment]
Problem was resolved. I think it was the pycharm problem rather than the package. I installed anaconda and used the conda install to install the packages to the virtual env and just added path to the IDE and its worked. Thanks for your help.
